[versions]
agp = "8.4.0"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.20"
glide = "4.16.0"
okhttp = "4.12.0"
retrofit = "2.11.0"
kotlinx_coroutines = "1.8.0"
androidx_core = "1.13.1"
androidx_preference = "1.2.1"
androidx_appcompat = "1.6.1"
androidx_constraintlayout = "2.1.4"
androidx_lifecycle = "2.7.0"
androidx_swiperefreshlayout = "1.1.0"
androidx_paging = "3.2.1"
androidx_activity = "1.9.0"
androidx_fragment = "1.6.2"
androidx_work = "2.9.0"
androidx_palette = "1.0.0"
androidx_room = "2.6.1"
androidx_material = "1.11.0"
androidx_flexbox = "3.0.0"
gson = "2.10.1"
persistentCookieJar = "1.0.1"
glide_transformations = "4.3.0"
gesture_views = "2.8.3"
jsoup = "1.17.2"
uCrop = "2020.09.28"
github_api = "1.321"
junit = "4.13.2"
androidx_test_ext_junit = "1.1.5"
androidx_test_espresso = "3.5.1"

[libraries]
kotlinx_coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_coroutines" }
kotlinx_coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx_coroutines" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx_preference_ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx_preference" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_appcompat" }
androidx_constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx_constraintlayout" }
androidx_lifecycle_livedata_ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx_lifecycle" }
androidx_lifecycle_viewmodel_ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx_lifecycle" }
androidx_lifecycle_process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx_lifecycle" }
androidx_swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx_swiperefreshlayout" }
androidx_paging_runtime_ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx_paging" }
androidx_activity_ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx_activity" }
androidx_fragment_ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx_fragment" }
androidx_work_runtime_ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx_work" }
androidx_palette_ktx = { module = "androidx.palette:palette-ktx", version.ref = "androidx_palette" }
androidx_room_runtime = { module = "androidx.room:room-runtime", version.ref = "androidx_room" }
androidx_room_compiler = { module = "androidx.room:room-compiler", version.ref = "androidx_room" }
androidx_room_ktx = { module = "androidx.room:room-ktx", version.ref = "androidx_room" }
androidx_room_paging = { module = "androidx.room:room-paging", version.ref = "androidx_room" }
androidx_material = { module = "com.google.android.material:material", version.ref = "androidx_material" }
androidx_flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "androidx_flexbox" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp_logging_interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit_converter_gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit_converter_scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide_okhttp3_integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide_ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide_transformations = { module = "jp.wasabeef:glide-transformations", version.ref = "glide_transformations" }
persistentCookieJar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentCookieJar" }
gesture_views = { module = "com.alexvasilkov:gesture-views", version.ref = "gesture_views" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
ucrop = { module = "com.github.yueeng:uCrop", version.ref = "uCrop" }
github_api = { module = "org.kohsuke:github-api", version.ref = "github_api" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx_test_ext_junit" }
androidx_test_espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx_test_espresso" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleDevtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }